# Generated by Django 4.2.6 on 2023-11-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('accountNo', models.CharField(max_length=20)),
            ],
        ),
    ]
