# Generated by Django 4.2.6 on 2023-11-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_registration_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Male', ',Male'), ('Female', 'Female'), ('Other', 'Other')], default='NaN', max_length=10),
        ),
    ]
